// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfNFS5-Uv1tLpkw2JU2tng7nlAijMAf04',
    appId: '1:132222798964:web:6a76d8c39b30a00c359521',
    messagingSenderId: '132222798964',
    projectId: 'ankur-e06b6',
    authDomain: 'ankur-e06b6.firebaseapp.com',
    storageBucket: 'ankur-e06b6.firebasestorage.app',
    measurementId: 'G-J36TLSS6H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATpor-gCQDtVChpaZy9uzNmKZ6xuq0dkk',
    appId: '1:132222798964:android:46e8a49385636d3d359521',
    messagingSenderId: '132222798964',
    projectId: 'ankur-e06b6',
    storageBucket: 'ankur-e06b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsb9F4tBl55VOUn-qpF6svwzJhVbx7mM8',
    appId: '1:132222798964:ios:30c8e99827598730359521',
    messagingSenderId: '132222798964',
    projectId: 'ankur-e06b6',
    storageBucket: 'ankur-e06b6.firebasestorage.app',
    iosBundleId: 'com.example.peddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsb9F4tBl55VOUn-qpF6svwzJhVbx7mM8',
    appId: '1:132222798964:ios:30c8e99827598730359521',
    messagingSenderId: '132222798964',
    projectId: 'ankur-e06b6',
    storageBucket: 'ankur-e06b6.firebasestorage.app',
    iosBundleId: 'com.example.peddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfNFS5-Uv1tLpkw2JU2tng7nlAijMAf04',
    appId: '1:132222798964:web:6c7452d3e1457fb3359521',
    messagingSenderId: '132222798964',
    projectId: 'ankur-e06b6',
    authDomain: 'ankur-e06b6.firebaseapp.com',
    storageBucket: 'ankur-e06b6.firebasestorage.app',
    measurementId: 'G-VLFY6N5DJC',
  );
}
